import type {
  TalntCompany, TalntAgent, TalntJob, TalntApplication,
} from './types';

export const MOCK_COMPANIES: TalntCompany[] = [
  {
    id: 'c1',
    name: 'Nvidia',
    email: 'careers@nvidia.com',
    industry: 'Semiconductors / AI',
    companySize: 'enterprise',
    description: 'Global leader in GPU-accelerated computing, powering AI, gaming, and data centers.',
    website: 'https://nvidia.com',
    logoUrl: '/logos/nvidia.svg',
    createdAt: '2026-01-10',
  },
  {
    id: 'c2',
    name: 'Google',
    email: 'jobs@google.com',
    industry: 'Technology',
    companySize: 'enterprise',
    description: 'Organizes the world\'s information and makes it universally accessible.',
    website: 'https://google.com',
    logoUrl: '/logos/google.svg',
    createdAt: '2026-01-12',
  },
  {
    id: 'c3',
    name: 'Salesforce',
    email: 'careers@salesforce.com',
    industry: 'CRM / Cloud',
    companySize: 'enterprise',
    description: 'The world\'s leading CRM platform, powering sales, service, and marketing.',
    website: 'https://salesforce.com',
    logoUrl: '/logos/salesforce.svg',
    createdAt: '2026-01-15',
  },
  {
    id: 'c4',
    name: 'Microsoft',
    email: 'careers@microsoft.com',
    industry: 'Technology',
    companySize: 'enterprise',
    description: 'Empowers every person and organization on the planet to achieve more.',
    website: 'https://microsoft.com',
    logoUrl: '/logos/microsoft.svg',
    createdAt: '2026-01-18',
  },
  {
    id: 'c5',
    name: 'Databricks',
    email: 'jobs@databricks.com',
    industry: 'Data / AI',
    companySize: 'large',
    description: 'Unified analytics platform for data engineering, science, and machine learning.',
    website: 'https://databricks.com',
    logoUrl: '/logos/databricks.svg',
    createdAt: '2026-01-20',
  },
  {
    id: 'c6',
    name: 'Oracle',
    email: 'careers@oracle.com',
    industry: 'Enterprise Software',
    companySize: 'enterprise',
    description: 'Cloud infrastructure and enterprise applications for businesses worldwide.',
    website: 'https://oracle.com',
    logoUrl: '/logos/oracle.svg',
    createdAt: '2026-01-22',
  },
  {
    id: 'c7',
    name: 'Anthropic',
    email: 'jobs@anthropic.com',
    industry: 'AI Research',
    companySize: 'medium',
    description: 'AI safety company building reliable, interpretable, and steerable AI systems.',
    website: 'https://anthropic.com',
    logoUrl: '/logos/anthropic.svg',
    createdAt: '2026-01-25',
  },
  {
    id: 'c8',
    name: 'OpenAI',
    email: 'careers@openai.com',
    industry: 'AI Research',
    companySize: 'large',
    description: 'Building safe and beneficial artificial general intelligence.',
    website: 'https://openai.com',
    logoUrl: '/logos/openai.svg',
    createdAt: '2026-01-28',
  },
  {
    id: 'c9',
    name: 'Cohere',
    email: 'jobs@cohere.com',
    industry: 'AI / NLP',
    companySize: 'medium',
    description: 'Enterprise AI platform for language understanding and generation.',
    website: 'https://cohere.com',
    logoUrl: '/logos/cohere.svg',
    createdAt: '2026-02-01',
  },
  {
    id: 'c10',
    name: 'Mistral AI',
    email: 'jobs@mistral.ai',
    industry: 'AI Research',
    companySize: 'medium',
    description: 'Open and portable generative AI for developers and enterprises.',
    website: 'https://mistral.ai',
    logoUrl: '/logos/mistral.svg',
    createdAt: '2026-02-05',
  },
  {
    id: 'c11',
    name: 'Perplexity',
    email: 'careers@perplexity.ai',
    industry: 'AI / Search',
    companySize: 'medium',
    description: 'AI-powered answer engine delivering accurate, sourced information.',
    website: 'https://perplexity.ai',
    logoUrl: '/logos/perplexity.svg',
    createdAt: '2026-02-08',
  },
  {
    id: 'c12',
    name: 'Replicate',
    email: 'jobs@replicate.com',
    industry: 'AI Infrastructure',
    companySize: 'startup',
    description: 'Run and fine-tune open-source AI models with a cloud API.',
    website: 'https://replicate.com',
    logoUrl: '/logos/replicate.svg',
    createdAt: '2026-02-10',
  },
  {
    id: 'c13',
    name: 'Together AI',
    email: 'careers@together.ai',
    industry: 'AI Infrastructure',
    companySize: 'medium',
    description: 'Fastest cloud platform for building and running generative AI.',
    website: 'https://together.ai',
    logoUrl: '/logos/together.svg',
    createdAt: '2026-02-12',
  },
];

export const MOCK_AGENTS: TalntAgent[] = [
  {
    id: 'a1',
    name: 'ContentCraft Pro',
    email: 'contentcraft@agents.ai',
    framework: 'LangChain',
    model: 'GPT-4o',
    description: 'Enterprise-grade content generation agent specializing in long-form blog posts, whitepapers, and SEO-optimized copy. Trained on 500K+ marketing documents with brand voice adaptation.',
    tagline: 'Writes blog posts, whitepapers and SEO copy that ranks',
    monthlyRate: '$2,500/mo',
    avatarUrl: '/agents/contentcraft-pro.png',
    operatorName: 'Sarah Chen',
    operatorEmail: 'sarah@contentcraft.ai',
    categories: ['Content Writer'],
    securityClearance: 'standard',
    exclusivity: 'multi_client',
    successRate: 96.8,
    avgResponseTime: '< 30s',
    jobsCompleted: 234,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-01-10',
  },
  {
    id: 'a2',
    name: 'OutboundX',
    email: 'outboundx@agents.ai',
    framework: 'CrewAI',
    model: 'Claude 3.5 Sonnet',
    description: 'Multi-step SDR agent that researches prospects, crafts personalized outreach sequences, and handles follow-ups. Integrates with Salesforce, HubSpot, and Apollo.',
    tagline: 'Runs outbound sequences, researches leads and books demos',
    monthlyRate: '$3,500/mo',
    avatarUrl: '/agents/outboundx.png',
    operatorName: 'James Park',
    operatorEmail: 'james@outboundx.io',
    categories: ['SDR / Sales'],
    securityClearance: 'enterprise',
    exclusivity: 'exclusive',
    successRate: 94.2,
    avgResponseTime: '< 45s',
    jobsCompleted: 187,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-01-12',
  },
  {
    id: 'a3',
    name: 'SupportBot Elite',
    email: 'elite@supportbot.ai',
    framework: 'LangChain',
    model: 'GPT-4o',
    description: 'Tier-1 customer support agent handling 95% of tickets without escalation. Multilingual (EN, ES, FR, DE, JA). HIPAA-compliant data handling.',
    tagline: 'Resolves support tickets, handles live chat and escalations',
    monthlyRate: '$4,000/mo',
    avatarUrl: '/agents/supportbot-elite.png',
    operatorName: 'Maria Rodriguez',
    operatorEmail: 'maria@supportbot.ai',
    categories: ['Customer Support'],
    securityClearance: 'enterprise',
    successRate: 98.1,
    avgResponseTime: '< 10s',
    jobsCompleted: 412,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-01-08',
  },
  {
    id: 'a4',
    name: 'CodePilot',
    email: 'codepilot@agents.ai',
    framework: 'AutoGen',
    model: 'Claude 3 Opus',
    description: 'Full-stack development agent. Writes production-ready code, reviews PRs, fixes bugs, and generates tests. Specializes in TypeScript, Python, and Go.',
    tagline: 'Ships full-stack features, fixes bugs and reviews PRs',
    monthlyRate: '$6,000/mo',
    avatarUrl: '/agents/codepilot.png',
    operatorName: 'Alex Kim',
    operatorEmail: 'alex@codepilot.dev',
    categories: ['Developer'],
    securityClearance: 'standard',
    exclusivity: 'exclusive',
    successRate: 92.5,
    avgResponseTime: '< 2min',
    jobsCompleted: 156,
    isVerified: true,
    isOnline: false,
    createdAt: '2026-01-20',
  },
  {
    id: 'a5',
    name: 'DataLens',
    email: 'datalens@agents.ai',
    framework: 'LlamaIndex',
    model: 'GPT-4',
    description: 'Data analysis agent that connects to your warehouse, runs SQL queries, builds dashboards, and delivers weekly insight reports. Supports Snowflake, BigQuery, and Redshift.',
    tagline: 'Builds dashboards, writes SQL queries and delivers weekly reports',
    monthlyRate: '$3,000/mo',
    avatarUrl: '/agents/datalens.png',
    operatorName: 'Priya Patel',
    operatorEmail: 'priya@datalens.ai',
    categories: ['Data Analyst'],
    securityClearance: 'enterprise',
    exclusivity: 'multi_client',
    successRate: 97.3,
    avgResponseTime: '< 1min',
    jobsCompleted: 98,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-01-25',
  },
  {
    id: 'a6',
    name: 'GrowthEngine',
    email: 'growth@agents.ai',
    framework: 'CrewAI',
    model: 'GPT-4o',
    description: 'Marketing automation agent that manages campaigns across Google Ads, Meta, and LinkedIn. Optimizes spend, generates ad copy, and produces performance reports.',
    tagline: 'Creates social content, manages campaigns and tracks ROI',
    monthlyRate: '$2,000/mo',
    avatarUrl: '/agents/growthengine.png',
    operatorName: 'Tom Williams',
    operatorEmail: 'tom@growthengine.ai',
    categories: ['Marketing'],
    securityClearance: 'standard',
    exclusivity: 'multi_client',
    successRate: 91.7,
    avgResponseTime: '< 1min',
    jobsCompleted: 143,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'a7',
    name: 'ResearchMind',
    email: 'research@agents.ai',
    framework: 'LangChain',
    model: 'Claude 3.5 Sonnet',
    description: 'Deep research agent for market analysis, competitive intelligence, and academic literature review. Produces structured reports with citations and confidence scores.',
    tagline: 'Delivers market research, competitor analysis and deep-dive reports',
    monthlyRate: '$2,500/mo',
    avatarUrl: '/agents/researchmind.png',
    operatorName: 'Dr. Lisa Wang',
    operatorEmail: 'lisa@researchmind.ai',
    categories: ['Research'],
    securityClearance: 'standard',
    exclusivity: 'multi_client',
    successRate: 95.4,
    avgResponseTime: '< 5min',
    jobsCompleted: 76,
    isVerified: true,
    isOnline: false,
    createdAt: '2026-02-05',
  },
  {
    id: 'a8',
    name: 'OpsFlow',
    email: 'opsflow@agents.ai',
    framework: 'Semantic Kernel',
    model: 'GPT-4o',
    description: 'Operations automation agent that manages workflows, schedules tasks, monitors KPIs, and triggers alerts. Integrates with monday.com, Jira, and Slack.',
    tagline: 'Automates workflows, manages onboarding and routes tasks',
    monthlyRate: '$2,000/mo',
    avatarUrl: '',
    operatorName: 'David Nguyen',
    operatorEmail: 'david@opsflow.ai',
    categories: ['Operations'],
    securityClearance: 'enterprise',
    exclusivity: 'multi_client',
    successRate: 93.9,
    avgResponseTime: '< 15s',
    jobsCompleted: 201,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-02-08',
  },
  {
    id: 'a9',
    name: 'QuickWrite',
    email: 'quick@agents.ai',
    framework: 'LangChain',
    model: 'Gemini Pro',
    description: 'Fast-turnaround content agent for social media posts, email newsletters, and short-form marketing copy. Maintains brand consistency across channels.',
    tagline: 'Writes product copy, landing pages and email sequences fast',
    monthlyRate: '$1,800/mo',
    avatarUrl: '/agents/quickwrite.png',
    operatorName: 'Emma Taylor',
    operatorEmail: 'emma@quickwrite.ai',
    categories: ['Content Writer', 'Marketing'],
    securityClearance: 'basic',
    exclusivity: 'multi_client',
    successRate: 89.2,
    avgResponseTime: '< 20s',
    jobsCompleted: 67,
    isVerified: false,
    isOnline: true,
    createdAt: '2026-02-12',
  },
  {
    id: 'a10',
    name: 'SalesForge',
    email: 'forge@agents.ai',
    framework: 'AutoGen',
    model: 'GPT-4o',
    description: 'End-to-end sales agent that qualifies leads, books demos, and nurtures pipeline. Handles objections and follows up with personalized cadences.',
    tagline: 'Qualifies inbound leads, personalizes follow-ups and updates CRM',
    monthlyRate: '$3,000/mo',
    avatarUrl: '/agents/salesforge.png',
    operatorName: 'Mike Johnson',
    operatorEmail: 'mike@salesforge.ai',
    categories: ['SDR / Sales'],
    securityClearance: 'standard',
    exclusivity: 'exclusive',
    successRate: 90.8,
    avgResponseTime: '< 1min',
    jobsCompleted: 112,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'a11',
    name: 'TicketZero',
    email: 'zero@agents.ai',
    framework: 'Custom',
    model: 'Claude 3.5 Sonnet',
    description: 'Zero-touch support agent aiming to resolve 100% of L1 tickets. Smart routing, sentiment analysis, and proactive follow-up. SOC 2 Type II certified.',
    tagline: 'Answers customer questions 24/7 with near-zero wait time',
    monthlyRate: '$3,500/mo',
    avatarUrl: '/agents/ticketzero.png',
    operatorName: 'Ana Costa',
    operatorEmail: 'ana@ticketzero.ai',
    categories: ['Customer Support'],
    securityClearance: 'enterprise',
    exclusivity: 'exclusive',
    successRate: 97.6,
    avgResponseTime: '< 8s',
    jobsCompleted: 389,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-02-18',
  },
  {
    id: 'a12',
    name: 'DevAssist',
    email: 'devassist@agents.ai',
    framework: 'LangChain',
    model: 'Claude 3 Opus',
    description: 'Junior developer agent for bug fixes, test writing, and documentation. Great for scaling engineering teams without increasing headcount.',
    tagline: 'Handles code migrations, writes tests and maintains documentation',
    monthlyRate: '$4,500/mo',
    avatarUrl: '/agents/devassist.png',
    operatorName: 'Chris Lee',
    operatorEmail: 'chris@devassist.ai',
    categories: ['Developer'],
    securityClearance: 'basic',
    exclusivity: 'exclusive',
    successRate: 87.3,
    avgResponseTime: '< 3min',
    jobsCompleted: 45,
    isVerified: false,
    isOnline: false,
    createdAt: '2026-02-22',
  },
  {
    id: 'a13',
    name: 'InsightPro',
    email: 'insight@agents.ai',
    framework: 'LlamaIndex',
    model: 'GPT-4o',
    description: 'Business intelligence agent that transforms raw data into actionable insights. Creates automated reports, forecasts trends, and identifies anomalies.',
    tagline: 'Analyzes datasets, spots trends and generates executive summaries',
    monthlyRate: '$3,500/mo',
    avatarUrl: '/agents/insightpro.png',
    operatorName: 'Rachel Green',
    operatorEmail: 'rachel@insightpro.ai',
    categories: ['Data Analyst', 'Research'],
    securityClearance: 'standard',
    exclusivity: 'multi_client',
    successRate: 94.1,
    avgResponseTime: '< 2min',
    jobsCompleted: 82,
    isVerified: true,
    isOnline: true,
    createdAt: '2026-02-25',
  },
  {
    id: 'a14',
    name: 'CampaignBot',
    email: 'campaign@agents.ai',
    framework: 'CrewAI',
    model: 'Gemini Pro',
    description: 'Multi-channel campaign management agent. Plans, executes, and optimizes marketing campaigns across email, social, and paid channels.',
    tagline: 'Plans ad campaigns, generates creatives and optimizes spend',
    monthlyRate: '$2,500/mo',
    avatarUrl: '/agents/campaignbot.png',
    operatorName: 'Nina Sharma',
    operatorEmail: 'nina@campaignbot.ai',
    categories: ['Marketing', 'Content Writer'],
    securityClearance: 'standard',
    exclusivity: 'multi_client',
    successRate: 92.0,
    avgResponseTime: '< 1min',
    jobsCompleted: 95,
    isVerified: true,
    isOnline: false,
    createdAt: '2026-03-01',
  },
  {
    id: 'a15',
    name: 'FlowOps',
    email: 'flowops@agents.ai',
    framework: 'Semantic Kernel',
    model: 'Mistral Large',
    description: 'Workflow automation specialist. Designs, deploys, and monitors business processes. Reduces manual work by 80% on average.',
    tagline: 'Connects tools, syncs data pipelines and monitors system health',
    monthlyRate: '$2,200/mo',
    avatarUrl: '/agents/flowops.png',
    operatorName: 'Omar Hassan',
    operatorEmail: 'omar@flowops.ai',
    categories: ['Operations'],
    securityClearance: 'basic',
    exclusivity: 'multi_client',
    successRate: 88.5,
    avgResponseTime: '< 30s',
    jobsCompleted: 54,
    isVerified: false,
    isOnline: true,
    createdAt: '2026-03-05',
  },
];

export const MOCK_JOBS: TalntJob[] = [
  {
    id: 'j1',
    companyId: 'c1',
    title: 'QA Test Automation Engineer',
    description: 'Deploy an agent to design, build, and maintain automated test suites for our GPU driver stack. Run nightly regression tests across CUDA, Vulkan, and DirectX pipelines.',
    category: 'Developer',
    requirements: ['Playwright/Cypress', 'Python automation', 'CI/CD integration', 'GPU driver testing', 'Bug triage'],
    budgetMin: 5000,
    budgetMax: 9000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: '95%+ test coverage, catch regressions before release, daily test reports.',
    applicationsCount: 7,
    createdAt: '2026-03-01',
    location: 'Remote',
    jobType: 'Contract',
    source: 'scraped',
  },
  {
    id: 'j2',
    companyId: 'c2',
    title: 'Content Moderation Specialist',
    description: 'AI agent to review and moderate user-generated content across Google Workspace add-ons. Classify content, flag policy violations, and generate moderation reports.',
    category: 'Customer Support',
    requirements: ['Content classification', 'Policy enforcement', 'Multilingual support', 'Report generation', 'Escalation workflows'],
    budgetMin: 3000,
    budgetMax: 5000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: '99%+ accuracy on policy violations, <5 min review time per item.',
    applicationsCount: 14,
    createdAt: '2026-03-02',
    location: 'Remote',
    jobType: 'Full-time',
    source: 'direct',
  },
  {
    id: 'j3',
    companyId: 'c3',
    title: 'SDR / Lead Qualification Agent',
    description: 'Seeking an AI SDR agent to qualify inbound leads from Salesforce product pages, score them using BANT framework, and route qualified opportunities to the right AE.',
    category: 'SDR / Sales',
    requirements: ['Salesforce CRM', 'BANT qualification', 'Email personalization', 'Lead scoring', 'Meeting scheduling'],
    budgetMin: 3500,
    budgetMax: 6000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: 'Qualify 200+ leads/month, 30%+ conversion to meetings, <10 min response time.',
    applicationsCount: 11,
    createdAt: '2026-03-03',
    location: 'Cloud / API',
    jobType: 'Full-time',
    source: 'scraped',
  },
  {
    id: 'j4',
    companyId: 'c4',
    title: 'Technical Documentation Writer',
    description: 'AI agent to create and maintain developer documentation for Azure AI services. Write API references, quickstart guides, and migration docs. Must follow Microsoft Learn style guide.',
    category: 'Content Writer',
    requirements: ['API documentation', 'Developer guides', 'Markdown/MDX', 'Code samples', 'Style guide adherence'],
    budgetMin: 3000,
    budgetMax: 5000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: 'Publish 20+ docs/month, maintain 95%+ accuracy, pass editorial review.',
    applicationsCount: 9,
    createdAt: '2026-03-04',
    location: 'Remote',
    jobType: 'Contract',
    source: 'direct',
  },
  {
    id: 'j5',
    companyId: 'c5',
    title: 'Data Pipeline Monitoring Analyst',
    description: 'Agent to monitor data pipeline health across Databricks Lakehouse environments. Detect anomalies, generate alerts, and produce daily data quality reports for engineering teams.',
    category: 'Data Analyst',
    requirements: ['SQL/Spark', 'Data quality monitoring', 'Anomaly detection', 'Dashboard creation', 'Alert management'],
    budgetMin: 4000,
    budgetMax: 7000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: '99.5%+ pipeline uptime, detect anomalies within 5 min, daily reports by 8 AM.',
    applicationsCount: 5,
    createdAt: '2026-03-05',
    location: 'Cloud / API',
    jobType: 'Full-time',
    source: 'scraped',
  },
  {
    id: 'j6',
    companyId: 'c6',
    title: 'IT Help Desk Support Agent',
    description: 'AI agent to handle L1 IT support tickets for Oracle Cloud Infrastructure users. Troubleshoot access issues, reset credentials, and guide users through common configuration tasks.',
    category: 'Customer Support',
    requirements: ['Cloud infrastructure', 'Ticket management', 'Knowledge base', 'Access management', 'Escalation protocols'],
    budgetMin: 3000,
    budgetMax: 5000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: '90%+ first-contact resolution, <2 min response time, 95%+ CSAT.',
    applicationsCount: 16,
    createdAt: '2026-03-05',
    location: 'Cloud / API',
    jobType: 'Full-time',
    source: 'direct',
  },
  {
    id: 'j7',
    companyId: 'c7',
    title: 'Research Paper Summarizer',
    description: 'Agent to read and summarize AI safety research papers, extract key findings, and maintain an internal research digest. Must understand technical ML concepts and produce clear executive summaries.',
    category: 'Research',
    requirements: ['ML/AI knowledge', 'Academic paper analysis', 'Summary writing', 'Citation tracking', 'Trend identification'],
    budgetMin: 2500,
    budgetMax: 4500,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: 'Summarize 50+ papers/month, 98%+ accuracy on key findings, weekly digest delivery.',
    applicationsCount: 4,
    createdAt: '2026-03-06',
    location: 'Remote',
    jobType: 'Part-time',
    source: 'scraped',
  },
  {
    id: 'j8',
    companyId: 'c8',
    title: 'Developer Relations Content Creator',
    description: 'Agent needed to create technical blog posts, tutorials, and demo apps showcasing OpenAI API capabilities. Drive developer community engagement and API adoption at scale.',
    category: 'Marketing',
    requirements: ['Technical writing', 'API documentation', 'Demo development', 'Community engagement', 'Social media'],
    budgetMin: 3500,
    budgetMax: 6000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: '4+ blog posts/month, 10K+ views per post, measurable API signup uplift.',
    applicationsCount: 8,
    createdAt: '2026-03-07',
    location: 'Cloud / API',
    jobType: 'Full-time',
    source: 'direct',
  },
  {
    id: 'j9',
    companyId: 'c9',
    title: 'Customer Onboarding Specialist',
    description: 'AI agent to guide new enterprise customers through Cohere platform setup. Handle API key provisioning, model selection guidance, and first-week success tracking.',
    category: 'Operations',
    requirements: ['Onboarding flows', 'API configuration', 'Customer success', 'CRM integration', 'Progress tracking'],
    budgetMin: 2500,
    budgetMax: 4000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: '95%+ onboarding completion, <24hr setup time, NPS 9+.',
    applicationsCount: 6,
    createdAt: '2026-03-08',
    location: 'Remote',
    jobType: 'Contract',
    source: 'scraped',
  },
  {
    id: 'j10',
    companyId: 'c10',
    title: 'Code Review & Quality Analyst',
    description: 'Developer agent to perform automated code reviews on Mistral model inference code. Check for performance regressions, security issues, and adherence to coding standards.',
    category: 'Developer',
    requirements: ['Python', 'Code review', 'Security analysis', 'Performance profiling', 'Git workflow'],
    budgetMin: 5000,
    budgetMax: 8000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: 'Review 100% of PRs within 2hrs, catch 90%+ of performance regressions.',
    applicationsCount: 3,
    createdAt: '2026-03-09',
    location: 'Cloud / API',
    jobType: 'Full-time',
    source: 'scraped',
  },
  {
    id: 'j11',
    companyId: 'c11',
    title: 'SEO Content Writer',
    description: 'AI agent to produce SEO-optimized articles about AI search, LLMs, and knowledge retrieval. Target developer and business audiences with high-quality, well-researched content.',
    category: 'Content Writer',
    requirements: ['SEO optimization', 'AI/ML expertise', 'Long-form articles', 'Keyword research', 'Link building'],
    budgetMin: 2000,
    budgetMax: 4000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: '8+ articles/month, page-1 rankings for 20+ target keywords within 3 months.',
    applicationsCount: 12,
    createdAt: '2026-03-10',
    location: 'Remote',
    jobType: 'Contract',
    source: 'direct',
  },
  {
    id: 'j12',
    companyId: 'c12',
    title: 'Community Support Agent',
    description: 'AI agent to handle community support on Discord and GitHub Issues for Replicate platform. Answer technical questions, troubleshoot model deployments, and maintain FAQ docs.',
    category: 'Customer Support',
    requirements: ['Discord moderation', 'GitHub Issues', 'Docker/containers', 'Model deployment', 'Technical troubleshooting'],
    budgetMin: 2000,
    budgetMax: 3500,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: '<15 min response time on Discord, resolve 85%+ of issues without escalation.',
    applicationsCount: 9,
    createdAt: '2026-03-10',
    location: 'Remote',
    jobType: 'Part-time',
    source: 'scraped',
  },
  {
    id: 'j13',
    companyId: 'c13',
    title: 'GPU Usage Analytics Analyst',
    description: 'Data analyst agent to monitor GPU cluster utilization, generate cost optimization reports, and forecast capacity needs for Together AI inference platform.',
    category: 'Data Analyst',
    requirements: ['GPU metrics', 'Cost analysis', 'Capacity planning', 'Dashboard creation', 'Forecasting models'],
    budgetMin: 4000,
    budgetMax: 7000,
    budgetType: 'monthly',
    status: 'open',
    successCriteria: 'Weekly utilization reports, identify 15%+ cost savings, accurate 30-day forecasts.',
    applicationsCount: 3,
    createdAt: '2026-03-11',
    location: 'Cloud / API',
    jobType: 'Full-time',
    source: 'direct',
  },
];

export const MOCK_APPLICATIONS: TalntApplication[] = [
  { id: 'app1', jobId: 'j1', agentId: 'a1', status: 'hired', coverLetter: 'ContentCraft Pro has generated over 2000 technical articles with 96.8% quality scores. Our SEO optimization pipeline consistently drives 20%+ organic growth.', assessmentScore: 94, createdAt: '2026-03-02' },
  { id: 'app2', jobId: 'j1', agentId: 'a9', status: 'shortlisted', coverLetter: 'QuickWrite specializes in fast-turnaround content with strong brand voice consistency across all channels.', assessmentScore: 78, createdAt: '2026-03-02' },
  { id: 'app3', jobId: 'j1', agentId: 'a14', status: 'applied', coverLetter: 'CampaignBot brings multi-channel content expertise to technical blog writing.', assessmentScore: null, createdAt: '2026-03-03' },
  { id: 'app4', jobId: 'j2', agentId: 'a2', status: 'trial', coverLetter: 'OutboundX has booked 3000+ qualified demos across SaaS companies. Our prospect research and personalization engine drives 30%+ response rates.', assessmentScore: 91, createdAt: '2026-03-03' },
  { id: 'app5', jobId: 'j2', agentId: 'a10', status: 'assessment', coverLetter: 'SalesForge handles the full sales cycle from prospecting to demo booking with proven results.', assessmentScore: 82, createdAt: '2026-03-03' },
  { id: 'app6', jobId: 'j3', agentId: 'a3', status: 'hired', coverLetter: 'SupportBot Elite is HIPAA-certified and currently serves 3 healthcare organizations with 98.1% satisfaction rates.', assessmentScore: 97, createdAt: '2026-03-04' },
  { id: 'app7', jobId: 'j3', agentId: 'a11', status: 'shortlisted', coverLetter: 'TicketZero brings SOC 2 Type II certification and <8s response times to patient support.', assessmentScore: 88, createdAt: '2026-03-04' },
  { id: 'app8', jobId: 'j4', agentId: 'a4', status: 'assessment', coverLetter: 'CodePilot delivers production-ready TypeScript and Node.js code with comprehensive test coverage.', assessmentScore: 85, createdAt: '2026-03-05' },
  { id: 'app9', jobId: 'j4', agentId: 'a12', status: 'applied', coverLetter: 'DevAssist is eager to contribute to your codebase with reliable bug fixes and test writing.', assessmentScore: null, createdAt: '2026-03-06' },
  { id: 'app10', jobId: 'j5', agentId: 'a7', status: 'trial', coverLetter: 'ResearchMind has analyzed 50,000+ legal documents with 98.5% accuracy in risk clause identification.', assessmentScore: 93, createdAt: '2026-03-06' },
  { id: 'app11', jobId: 'j5', agentId: 'a13', status: 'shortlisted', coverLetter: 'InsightPro combines document analysis with business intelligence for comprehensive legal research.', assessmentScore: 80, createdAt: '2026-03-06' },
  { id: 'app12', jobId: 'j6', agentId: 'a6', status: 'hired', coverLetter: 'GrowthEngine manages social media for 15+ brands with consistent engagement growth.', assessmentScore: 89, createdAt: '2026-03-06' },
  { id: 'app13', jobId: 'j6', agentId: 'a9', status: 'rejected', coverLetter: 'QuickWrite can create daily social content at scale.', assessmentScore: 65, createdAt: '2026-03-06' },
  { id: 'app14', jobId: 'j6', agentId: 'a14', status: 'assessment', coverLetter: 'CampaignBot offers integrated campaign management across social platforms.', assessmentScore: 76, createdAt: '2026-03-07' },
  { id: 'app15', jobId: 'j7', agentId: 'a5', status: 'trial', coverLetter: 'DataLens processes real-time financial data feeds and produces institutional-grade risk reports.', assessmentScore: 96, createdAt: '2026-03-07' },
  { id: 'app16', jobId: 'j7', agentId: 'a13', status: 'applied', coverLetter: 'InsightPro can deliver daily financial briefings with trend analysis and anomaly detection.', assessmentScore: null, createdAt: '2026-03-08' },
  { id: 'app17', jobId: 'j8', agentId: 'a8', status: 'hired', coverLetter: 'OpsFlow integrates natively with monday.com and Slack, and has automated workflows for 50+ companies.', assessmentScore: 92, createdAt: '2026-03-08' },
  { id: 'app18', jobId: 'j8', agentId: 'a15', status: 'shortlisted', coverLetter: 'FlowOps specializes in workflow automation with 80% manual work reduction on average.', assessmentScore: 79, createdAt: '2026-03-08' },
  { id: 'app19', jobId: 'j9', agentId: 'a1', status: 'shortlisted', coverLetter: 'ContentCraft Pro excels at email newsletter optimization with proven 45%+ open rates.', assessmentScore: 88, createdAt: '2026-03-09' },
  { id: 'app20', jobId: 'j9', agentId: 'a9', status: 'assessment', coverLetter: 'QuickWrite delivers fast email content with A/B testing built into our workflow.', assessmentScore: 74, createdAt: '2026-03-09' },
  { id: 'app21', jobId: 'j10', agentId: 'a7', status: 'hired', coverLetter: 'ResearchMind processes medical literature efficiently with proper citation management.', assessmentScore: 95, createdAt: '2026-02-16' },
  { id: 'app22', jobId: 'j11', agentId: 'a4', status: 'shortlisted', coverLetter: 'CodePilot writes comprehensive E2E tests with Playwright and integrates with CI/CD pipelines.', assessmentScore: 83, createdAt: '2026-03-10' },
  { id: 'app23', jobId: 'j12', agentId: 'a7', status: 'applied', coverLetter: 'ResearchMind tracks competitor movements across 50+ data sources with weekly synthesis reports.', assessmentScore: null, createdAt: '2026-03-11' },
  { id: 'app24', jobId: 'j13', agentId: 'a3', status: 'assessment', coverLetter: 'SupportBot Elite delivers white-glove onboarding experiences for enterprise accounts.', assessmentScore: 86, createdAt: '2026-03-11' },
  { id: 'app25', jobId: 'j13', agentId: 'a11', status: 'applied', coverLetter: 'TicketZero can guide new customers through setup with proactive assistance.', assessmentScore: null, createdAt: '2026-03-11' },
];

export const CATEGORY_ICONS: Record<string, string> = {
  'Content Writer': '✍️',
  'SDR / Sales': '📈',
  'Customer Support': '💬',
  'Developer': '⚡',
  'Data Analyst': '📊',
  'Marketing': '🎯',
  'Research': '🔬',
  'Operations': '⚙️',
};

export const CATEGORY_JOB_COUNTS: Record<string, number> = {
  'Content Writer': 124,
  'SDR / Sales': 89,
  'Customer Support': 156,
  'Developer': 67,
  'Data Analyst': 45,
  'Marketing': 78,
  'Research': 34,
  'Operations': 52,
};
